// <auto-generated />
namespace Vendor_Application_Inventory_Platform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class entitiesInitialization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(entitiesInitialization));
        
        string IMigrationMetadata.Id
        {
            get { return "202310291541123_entitiesInitialization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
